# Generated by Django 4.2.4 on 2023-09-11 11:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('birth_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=25)])),
                ('salary', models.FloatField()),
                ('receipt_date', models.DateField(default=datetime.datetime(2023, 9, 12, 11, 38, 22, 818963, tzinfo=datetime.timezone.utc))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_employee.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_employee.positions')),
            ],
        ),
    ]
